# Generated by Django 5.1.5 on 2025-02-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_host_name', models.CharField(max_length=100, unique=True)),
                ('installed_apps', models.TextField(blank=True, null=True)),
                ('installation_status', models.BooleanField(default=False)),
                ('license_status', models.BooleanField(default=False)),
                ('allocation_status', models.BooleanField(default=False)),
                ('received_from_left_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('allocated_on', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('laptop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.laptop')),
            ],
        ),
    ]
