# Generated by Django 5.0.12 on 2025-02-14 08:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_host_name', models.CharField(max_length=100, unique=True)),
                ('installed_apps', models.TextField(blank=True, null=True)),
                ('installation_status', models.BooleanField(default=False)),
                ('license_status', models.CharField(default='Pending', max_length=50)),
                ('allocation_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('faulty', 'Faulty')], default='available', max_length=50)),
                ('received_from_left_employee', models.BooleanField(default=False)),
                ('faulty_status', models.BooleanField(default=False)),
                ('replacement_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_host_name', models.CharField(max_length=100, unique=True)),
                ('installed_apps', models.JSONField(default=list)),
                ('allocation_status', models.CharField(default='Available', max_length=50)),
                ('sophos_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('patch_manager_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('sase_proxy_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('summit_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('license_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Pending', max_length=10)),
                ('replaced_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_asset', to='accounts.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Deallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('deallocation_date', models.DateTimeField(auto_now_add=True)),
                ('data_transferred', models.BooleanField(default=False)),
                ('formatted', models.BooleanField(default=False)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('allocated_on', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('allocation_date', models.DateField(default=datetime.date.today)),
                ('laptop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
        ),
    ]
