# Generated by Django 5.1.5 on 2025-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_host_name', models.CharField(max_length=100)),
                ('installed_apps', models.TextField()),
                ('installation_status', models.CharField(max_length=50)),
                ('license_status', models.CharField(max_length=50)),
                ('allocation_status', models.CharField(max_length=50)),
                ('received_from_left_employee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
            ],
        ),
    ]
