# Generated by Django 5.1.5 on 2025-02-04 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='allocation_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='asset_host_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='installation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='installed_apps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='license_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='received_from_left_employee',
            field=models.BooleanField(default=False),
        ),
    ]
