# Generated by Django 5.1.5 on 2025-02-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_allocation_allocation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='allocation_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='installation_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='installed_apps',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='license_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='received_from_left_employee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
