# Generated by Django 5.0.12 on 2025-02-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250214_1511'),
    ]

    operations = [
    ]
