# Generated by Django 5.0.12 on 2025-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250214_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='adapter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='asset_category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='allocation',
            name='asset_tag_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocation',
            name='battery_sl',
            field=models.CharField(default='Not Available', max_length=255),
        ),
        migrations.AddField(
            model_name='allocation',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='emp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='hard_disk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='mouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocation',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='project_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocation',
            name='ram_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='request_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='short_term',
            field=models.BooleanField(default=False),
        ),
    ]
