# Generated by Django 5.1.5 on 2025-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_inventory_allocation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='faulty_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='replacement_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
