# Generated by Django 5.1.5 on 2025-02-05 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_laptop_faulty_status_laptop_replacement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='laptop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory'),
        ),
    ]
