# Generated by Django 5.1.5 on 2025-02-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_allocation_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='installation_status',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='installed_apps',
            field=models.JSONField(default=list),
        ),
    ]
