# Generated by Django 5.1.5 on 2025-02-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_inventory_installation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='received_from_left_employee',
        ),
    ]
