# Generated by Django 5.1.5 on 2025-02-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_inventory_received_from_left_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('faulty', 'Faulty')], default='available', max_length=50),
        ),
    ]
