# Generated by Django 5.1.5 on 2025-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_contact_number_allocation_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='user_confirmation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
