# Generated by Django 5.0.12 on 2025-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_allocation_user_confirmation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='engineer_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
