# Generated by Django 5.1.5 on 2025-02-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_inventory_last_assigned_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_assigned_engineer',
        ),
    ]
