# Generated by Django 5.0.12 on 2025-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_allocation_engineer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='project_specific',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
