# Generated by Django 5.0.12 on 2025-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_allocation_project_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='ram_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
