# Generated by Django 5.1.5 on 2025-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_inventory_last_assigned_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='license_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
