# Generated by Django 5.0.12 on 2025-03-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_allocation_ram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='bag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='mouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='short_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
