# Generated by Django 5.1.5 on 2025-02-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_laptop_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='patch_manager_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sase_proxy_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sophos_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='summit_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
