# Generated by Django 5.1.5 on 2025-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_inventory_patch_manager_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='license_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='patch_manager_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sase_proxy_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sophos_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='summit_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
    ]
