# Generated by Django 5.0.12 on 2025-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_processor_alter_allocation_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
    ]
