# Generated by Django 5.1.5 on 2025-02-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_inventory_license_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='data_transfer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_assigned_engineer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='allocation_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='installed_apps',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='license_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Pending', max_length=50),
        ),
    ]
