# Generated by Django 5.0.12 on 2025-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_allocation_processor_delete_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_host_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Deallocated', 'Deallocated'), ('Faulty', 'Faulty')], max_length=20)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('deallocation_date', models.DateField(blank=True, null=True)),
                ('faulty_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
