# Generated by Django 5.1.5 on 2025-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_inventory_data_transfer_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='data_transfer_status',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_assigned_engineer',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='allocation_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='installed_apps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='license_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
