# Generated by Django 5.0.12 on 2025-03-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_laptopinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaptopInventory',
        ),
    ]
