# Generated by Django 5.1.5 on 2025-02-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_inventory_data_transfer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('deallocation_date', models.DateTimeField(auto_now_add=True)),
                ('data_transferred', models.BooleanField(default=False)),
                ('formatted', models.BooleanField(default=False)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory')),
            ],
        ),
    ]
