# Generated by Django 5.0.12 on 2025-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_laptopinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_host_name', models.CharField(max_length=255)),
                ('allocation_status', models.CharField(choices=[('Allocated', 'Allocated'), ('Deallocated', 'Deallocated'), ('Faulty', 'Faulty')], default='Allocated', max_length=20)),
                ('allocated_date', models.DateField(blank=True, null=True)),
                ('deallocated_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
