# Generated by Django 5.1.5 on 2025-02-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_deallocation_data_transfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deallocation',
            name='data_transfer_status',
        ),
    ]
