# Generated by Django 5.0.12 on 2025-03-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_statistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
